core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from shop import views

# handler404 = "shop.views.handler404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = 'Wsports'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index_url'),
    path('brands/<slug:brand_name>/', views.BrandProductsView.as_view(), name='brand_url'),
    path('categories/<str:category_name>/', views.CategoryProductsView.as_view(), name='category_url'),
    path('product/<str:product_name>/', views.ProductDetailView.as_view(), name='product_url'),
    path('test_form/', views.test_model_form, name='form_url'),
    path('accounts/profile/', views.ProfileView.as_view(), name='profile'),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),
    path('add_to_cart/<int:product_id>', views.AddToCartView.as_view(), name='add_to_cart_url'),
    path('cart/delete/<int:product_variant_id>/', views.DeleteFromCartView.as_view(), name='product_delete_url'),
    path('cart/', views.CartView.as_view(), name='cart_url'),
    path('shipping_and_payment/', views.ShippingAndPaymentView.as_view(), name='shipping_and_payment_url'),
    path('change_count/<int:product_variant_id>/<str:count>/', views.ChangeCountView.as_view(), name='change_count_url'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout_url'),
    path('purchase/<int:id>', views.PurchaseView.as_view(), name='purchase_url'),
    path('success/', views.PaymentSuccessView.as_view(), name='payment_success_url'),
    path('failure/', views.PaymentFailureView.as_view(), name='payment_failure_url'),
    path('result/', views.PaymentResultView.as_view(), name="payment_result_url"),
    path('get_attribute_format/', views.GetAttributeFormatView.as_view(), name="get_attribute_format_url"),
    path('rent_product/<int:product_id>/', views.RentProductView.as_view(), name="rent_product"),
    path('rent/<int:product_variant_id>/', views.AcceptProductRentView.as_view(), name="rent_acception_url"),
    path('order_finish/', views.OrderFinishView.as_view(), name="order_finish_url"),
    path('delete_address/<int:address_id>/', views.DeleteAddressView.as_view(), name="delete_address_url"),
    path('find_weather_forecast/', views.FindWeatherForecastView.as_view(), name="find_weather_forecast_url"),
    path('search_for_products/', views.SearchForProducts.as_view(), name="search_for_products_url"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

shop/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import F, ExpressionWrapper, FloatField, Sum
# TODO: Модель пользователя: рост, вес, размер ноги, навыки катания и тп... Мази по температуре,
#  фильтры масок по освещенности

# Полиморфизм гарантирует, что объект может вести себя по-разному в разных условиях


# git init  git status  git add (. / Названия файлов и папок)  git commit -m "сообщение"
# git checkout (первые 5 цифр коммита / название ветки)  git log - посмотреть историю коммитов
# git checkout -b название_ветки — создать новую ветку
# git merge название_ветки — слить текущую ветку и указанную
# git pull — вытащить изменения с сервера
# git push — залить изменения на сервер
# git remote add origin адрес_сервера — добавления удаленного репозитория для обмена кодом
# git remote — просмотр списка удаленных репозиториев
# git remote -v — простотр адресов удаленных репозиториев для загрузки и выгрузки кода
# git clone адрес_репозитория — клонирование чужого репозитория


class Product(models.Model):
    """Модель товара"""
    name = models.CharField(verbose_name="Название", max_length=150, db_index=True)
    description = models.TextField(verbose_name="Описание", null=True, blank=True)
    price = models.FloatField(verbose_name="Цена", help_text="Цену указывать в рублях", db_index=True)

    photo = models.ImageField(upload_to="product_photos", verbose_name="Главное фото товара", default='/xtra/noimage.jpg')
    published = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    categories = models.ManyToManyField("Category", verbose_name="Категория товара", null=True,
                                 blank=True, db_index=True)
    tags = models.ManyToManyField('Tag', verbose_name='Тэг')
    brand = models.ForeignKey('Brand', on_delete=models.PROTECT, verbose_name='Бренд', null=True, blank=True)
    attributes = models.ManyToManyField("ProductAttribute", through='ProductAttributeValue')
    recommendations = models.ManyToManyField('Product', verbose_name='рекомендации к товару')
    # variants = models.ManyToManyField("ProductAttributeValue", verbose_name="Варианты продукта",
    #                                  through="ProductVariant", related_name="products")

    def __str__(self):
        return str(self.name)

    def add_attributes(self, *args, **kwargs):
        attribute_list = ProductAttribute.objects.filter(categories__in=self.categories.all())
        for attribute in attribute_list:
            if not attribute.is_choosable:
                ProductAttributeValue.objects.create(product=self, attribute=attribute)

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = ["-published"]


class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    count = models.PositiveSmallIntegerField(verbose_name="Количество", default=0)
    attribute_values = models.ManyToManyField("ProductAttribute", verbose_name="Значения параметров", through="VariantsAttributeValue")

    def __str__(self):
        return f"{self.product}: {', '.join([ str(attr_val.get_value()) for attr_val in self.variant_values.all()])}" #TODO: доделать метод и вывести выбираемые атрибуты на странице продукта на сайте

    def save(self, *args, **kwargs):
        created = not self.pk
        super(ProductVariant, self).save(*args, **kwargs)
        attribute_list = ProductAttribute.objects.filter(categories__in=self.product.categories.all())
        if created:
            for attribute in attribute_list:
                if attribute.is_choosable:
                    VariantsAttributeValue.objects.create(product_variant=self, attribute=attribute)
        return self


class ProductAttribute(models.Model):
    """Модель свойств (аттрибутов) продуктов """
    class AttributeType(models.TextChoices):
        INT = 'INT', 'Целое число'
        FLOAT = 'FLT', 'Дробное число'
        STRING = 'STR', 'Строковое значение'
        BOOLEAN = 'BLN', 'Да/Нет'
        VARIANTS = 'VRT', 'Набор вариантов'

    name = models.CharField(verbose_name='Название', max_length=150)
    categories = models.ManyToManyField('Category', verbose_name='Категория', blank=True)
    type = models.CharField(choices=AttributeType.choices, max_length=3)
    is_choosable = models.BooleanField(verbose_name="Выбираемый пользователем?", default=False)

    def __str__(self):
        return str(self.name)


class ChoosableAttributeOptions(models.Model):
    value = models.CharField(verbose_name="Значение", max_length=255)
    attribute = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE, verbose_name="Атрибут")

    class Meta:
        verbose_name = "Значение выбираемого атрибута"
        verbose_name_plural = "Значения выбираемых атрибутов"


    # def save(self, *args, **kwargs):
    #     print(args, kwargs)
    #     created = not self.pk
    #     super(ProductAttribute, self).save(*args, **kwargs)
    #     # super(ProductAttribute, self).save_related(*args, **kwargs)
    #     product_list = Product.objects.filter(category__in=self.categories.all())
    #     print(product_list, self.categories.all())
    #     if created:
    #         for product in product_list:
    #             ProductAttributeValue.objects.create(product=product, attribute=self)
    #     return self


class Category(models.Model):
    """Категория товара"""
    name = models.CharField(verbose_name="Название", max_length=150)
    description = models.TextField(verbose_name="Описание", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ['name']


class Tag(models.Model):
    """Тэг товара"""
    name = models.CharField(max_length=150, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "тэг"
        verbose_name_plural = "тэги"
        ordering = ['name']


class ProductPhoto(models.Model):
    """Детальное фото товара"""
    description = models.CharField(max_length=255, verbose_name='Описание', null=True, blank=True)
    product = models.ForeignKey("Product", on_delete=models.CASCADE, verbose_name="товар", related_name='images')
    photo = models.ImageField(verbose_name='Фотография', upload_to='photos')

    def __str__(self):
        return str(self.description)

    class Meta:
        verbose_name = "детальное фото"
        verbose_name_plural = "детальные фото"
        ordering = ['product']


class Customer(AbstractUser):
    """Новая модел пользователя"""
    phone = models.CharField(verbose_name="Телефон",
                             blank=True, max_length=12, null=True, )
    email = models.EmailField(verbose_name='email', unique=True)
    # visited_categories = models.ManyToManyField(Category, verbose_name='Посещенные категории', null=True, blank=True)

    #    purchases = models.ManyToManyField("Product", through="Purchase", verbose_name="Товары")

    def get_recommendations(self):
        return self.visited_categories[3]

    class Meta:
        verbose_name = "покупатель"
        verbose_name_plural = "покупатели"


# TODO: зашить внутрь системы список городов России
class Address(models.Model):
    """Модель адреса для оформления заказа"""
    city = models.CharField(max_length=100, verbose_name='Город')
    street = models.CharField(verbose_name='Улица', max_length=100)
    house = models.CharField(max_length=100, verbose_name='Дом')
    flat = models.PositiveSmallIntegerField(verbose_name='Квартира/Офис')
    contact = models.CharField(max_length=100, verbose_name='Контактное лицо')
    extra_phone = models.CharField(verbose_name='Доп телефон', max_length=12)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Клиент')

    def __str__(self):
        return f"г. {self.city}, {self.street}, д. {self.house}, кв/оф {self.flat}, получатель: {self.customer}"


class Brand(models.Model):
    """Бренд"""
    name = models.CharField(max_length=150, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    photo = models.ImageField(verbose_name='Фото', upload_to='brand_photos', null=True, blank=True, default="xtra/noimage.jpg")

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'бренд'
        verbose_name_plural = 'бренды'
        ordering = ['name']


class AttributeValue(models.Model):
    attribute = models.ForeignKey(ProductAttribute, verbose_name='аттрибут', on_delete=models.CASCADE)
    int_value = models.IntegerField(null=True, blank=True)
    float_value = models.FloatField(null=True, blank=True)
    str_value = models.CharField(max_length=150, null=True, blank=True)
    bool_value = models.BooleanField(null=True, blank=True)

    def __str__(self):
        if self.attribute.type == ProductAttribute.AttributeType.INT:
             value = self.int_value
        elif self.attribute.type == ProductAttribute.AttributeType.FLOAT:
             value = self.float_value
        elif self.attribute.type == ProductAttribute.AttributeType.STRING:
             value = self.str_value
        elif self.attribute.type == ProductAttribute.AttributeType.BOOLEAN:
             value = self.bool_value
        if self.attribute.type == ProductAttribute.AttributeType.VARIANTS:
             value = " "
        return f"{ self.attribute.name } { value }"

    def get_value(self):
        return self.int_value or self.float_value or self.str_value or self.bool_value

    class Meta:
        abstract = True


class ProductAttributeValue(AttributeValue):
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE,
                                related_name="attribute_values")

    class Meta:

shop/templates/cart.html
{% extends 'base.html' %}

{% block title %} {{ user.username }} - корзина {% endblock %}

{% block content %}
<div class="container">
    {% if order_set %}
    <ul class="list-group list-group-flush mt-5">
        {% for order in order_set %}

            <li class="list-group-item">

                    <a href="{% url 'Wsports:product_url' order.product_variant.product.name %}">
                        <div>
                            <div style="float: left; width: 70%; color: black;">
                                <p>Товар:&nbsp;{{ order.product_variant.product.name }}</p>
                                <p>{% for attr in order.product_variant.variant_values.all %}{{ attr }}: {{ attr.value }}, {% endfor %}</p>
                                <p>Цена:&nbsp;{{ order.product_variant.product.price }}</p>
                                <p>Количество:&nbsp;{{ order.count }} <a href="{% url 'Wsports:change_count_url' order.product_variant.id -1 %}">-</a> / <a href="{% url 'Wsports:change_count_url' order.product_variant.id 1 %}">+</a></p>
                                <p>Стоимость:&nbsp;{{ order.amount }}</p>
                                <p><a href="{% url 'Wsports:product_delete_url' order.product_variant.id %}">Убрать</a></p>

                            </div>
                                <img src="{{ order.product_variant.product.photo.url }}" alt="{{ order.product_variant.product.name }}" height="30%" width="auto" style="width: 20%; float: right; display: block;">

                        </div>
                    </a>
            </li>
        {% endfor %}
        </ul>

        <p><b>&nbsp;К оплате: {{ cart.get_total_amount }}</b></p>
        <a href="{% url 'Wsports:shipping_and_payment_url' %}"><button class="btn btn-success">Оформить</button></a>

    {% else %}
        <p class="mt-5"><b>Корзина пуста</b></p>
    {% endif %}
</div>
{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}Wsports: товары для зимнего спорта {% endblock %}
    {% block styles %}
        <link rel="stylesheet" href="{% static 'shop/css/index.css' %}">
    {% endblock %}
    {% block script%}
        <script src="https://api-maps.yandex.ru/2.1/?apikey=f35e0eea-4ac4-4e47-8b7a-dcc5104fcfa3&lang=ru_RU" type="text/javascript">
        </script>

        <script type="text/javascript">
            // Функция ymaps.ready() будет вызвана, когда
            // загрузятся все компоненты API, а также когда будет готово DOM-дерево.
            let placemark = null;
            ymaps.ready(init);
            function init(){
                // Создание карты.
                let myMap = new ymaps.Map("map", {
                    // Координаты центра карты.
                    // Порядок по умолчанию: «широта, долгота».
                    // Чтобы не определять координаты центра карты вручную,
                    // воспользуйтесь инструментом Определение координат.
                    center: [55.76, 37.64],
                    // Уровень масштабирования. Допустимые значения:
                    // от 0 (весь мир) до 19.
                    zoom: 7
                });

                myMap.events.add('click', function(e) {
                    let coords = e.get('coords');
                    let lat = document.getElementById("id_latitude");
                    let lon = document.getElementById("id_longitude");
                    lat.value = coords[0];
                    lon.value = coords[1];
                    if (placemark){
                        myMap.geoObjects.remove(placemark);
                    }
                    placemark = new ymaps.Placemark([coords[0], coords[1]],
                        {
                            hintContent: "Выбранное место катания",
                            balloonContent: "Место катания выбрано"
                        },
                        {
                            iconLayout: "default#image",
                            iconImageHref: "{% static 'images/skierIcon.png' %}",
                            iconImageSize: [60, 60]
                        });
                myMap.geoObjects.add(placemark);
                });

            }

        </script>
    {% endblock %}

{% block content %}

    <h1 class="">Wsports: товары для зимнего спорта</h1>
    <div class="last-added mt-5" align="center"><b>Последние добавленные товары</b></div>
    <div class="container">
        {% include 'product_list.html' %}
        <div class="row">
            <div class="col">
                <h2 style="width: 100%; text-align: center;">Подобрать инвентарь по погоде <a href="https://www.gismeteo.ru/"><img id="gismeteo-logo" src="https://logos-download.com/wp-content/uploads/2019/11/Gismeteo_Logo.png" alt="Gismeteo"></a></h2>
                <p style="width: 100%; text-align: center;">Выберите точку на карте и нажмите кнопку "Подобрать"</p>
                <div id="map" style="width: 600px; height: 400px; margin: 40px auto;"></div>

                <form action="{% url 'Wsports:find_weather_forecast_url' %}" method="POST">
                    {% csrf_token %}
                    {{ coords_form.as_p }}
                    <input type="submit" value="Подобрать" style="display: block; margin: 0 auto;">
                </form>


            </div>
        </div>
        <div class="row"><div class="col" align="center"><h2>Категории</h2></div></div>
        <div class="row mb-5">
            {% for category in category_list %}
                {% if forloop.counter0|divisibleby:"3" %}
                </div><div class="row my-5">
                {% endif %}
                <div class="card col-3 m-auto card-category" style="width: 18rem;">
                    {# <img src="{{ product.photo.url }}" class="card-img-top" alt="{{ product }}" width="70px" height="100px"/> #}
                    <div class="card-body">
                        <h3 class="card-title">{{ category.name|truncatewords:5 }}</h3>
                        <p class="card-text">{{ category.description|truncatewords:5 }}</p>
                        <a href="{% url 'Wsports:category_url' category_name=category.name %}" class="btn btn-primary detail-btn">Перейти</a>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="row"><div class="col" align="center"><h2>Бренды</h2></div></div>
        <div class="row mb-5">
            {% for brand in brand_list %}
                {% if forloop.counter0|divisibleby:"3" %}
                </div><div class="row my-5">
                {% endif %}
                <div class="card col-3 m-auto card-brand" style="width: 18rem;">
                    <img src="{{ brand.photo.url }}" class="card-img-top" alt="{{ brand }}" width="70px" height="100px"/>
                    <div class="card-body">
                        <h3 class="card-title">{{ brand.name|truncatewords:5 }}</h3>
                        <p class="card-text">{{ brand.description|truncatewords:5 }}</p>
                        <a href="{% url 'Wsports:brand_url' brand_name=brand.name %}" class="btn btn-primary detail-btn">Перейти</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/payment_failure.html
{% extends 'base.html' %}

{% block title %} Оплата не выполнена {% endblock %}

{% block content %}
    <div class="container">
        <p>Оплата заказа #{{ order }} не была выполнена</p>
    </div>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}
{% block title %} {{ product }} {% endblock %}



{% block content %}

<style>
    .tag {
        color: blue;
    }

    .ocount {
        color: red;
    }

    #btn-rent p {
        margin-bottom: 0;
    }

/*    .buttonn {*/
/*        background: white*/
/*       a.button: hover { background: rgb(80, 80, 80); }*/
/*       a.button: active { background: rgb(0, 0, 0); }*/
/*   }*/
</style>


<div class="container mt-5">
    <div class="row"><h1>{{ product.name }}</h1></div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-8"><img src="{{ product.photo.url }}" alt="{{ product }}" style="width: 100%;"/></div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="row my-5">
                        {% for image in product.images.all %}
                            {% if forloop.counter0|divisibleby:"2" %}
                            </div><div class="row my-5">
                            {% endif %}
                            <div class="card col-3 m-auto" style="width: 18rem;">
                                <img src="{{ image.photo.url }}" class="card-img-top" alt="{{ product }}" width="70px" height="100px"/>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="row">
                <div class="col">
                    <b><p>{{ product.brand }}</p></b>
                    <p>{{ product.description }}</p>
                    <p><b>{{ product.price }} <sup>руб</sup></b>
                            {% if product.count == 0 %}
                                <div class="ocount">нет в наличии</div>
                            {% else %}
                                <div>{{ product.count }} шт.</div>
                            {% endif %}</p>
                    {% for attr in product.attribute_values.all %}
                       <p>{{ attr.attribute.name }}:
                           {% if attr.attribute.type == 'INT' %}
                                {{ attr.int_value }}
                           {% elif attr.attribute.type == 'FLT' %}
                                {{ attr.float_value }}
                           {% elif attr.attribute.type == 'STR' %}
                                {{ attr.str_value }}
                           {% elif attr.attribute.type == 'BLN' %}
                                {% if attr.bool_value %} Да {% else %} Нет {% endif %}
                           {% elif attr.attribute.type == 'VRT' %}
                                {{ attr.str_value }}

                           {% endif %}
                       </p>
                    {% endfor %}
                    <form action="{% url 'Wsports:add_to_cart_url' product_id=product.id %}" method="POST" id="add_to_cart_form">
                        {% csrf_token %}

                        {% for variant in product.productvariant_set.first.variant_values.all %}
                            <p>
                                <label>{{ variant.attribute }}:</label>
                                <select name="attribute-{{ variant.attribute.id }}">
                                    {% for option in variant.attribute.choosableattributeoptions_set.all %}
                                        <option value="{{ option.value }}">{{ option.value }}</option>
                                    {% endfor %}
                                </select>
                            </p>
                        {% endfor %}

                        {% for tag in product.tags.all %}
                            <p class="tag">#{{ tag }}</p>
                        {% endfor %}
                        <div id="buttons-wrapper">
                            <input type="submit" class="btn btn-primary" value="Добавить">
                            <div class="btn btn-primary" id="btn-rent">
                                <p>В аренду</p>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
    {% if product.recommendations.all.count > 0 %}
    <h2 align="center">К этому товару мы рекомендуем:</h2>
    {% endif %}
    <div class="row my-5">
    {% for product in product.recommendations.all %}
        {% if forloop.counter0|divisibleby:"3" %}
        </div><div class="row my-5">
        {% endif %}
        <div class="card col-3 m-auto" style="">
            <a href="{% url 'Wsports:product_url' product_name=product.name %}" class="btn btn-primary detail-btn"
               style="background-color: white; border: none;">
                <img src="{{ product.photo.url }}" class="card-img-top" alt="{{ product }}"/>
                <div class="card-body">
                    <h3 class="card-title" style="color: black;">{{ product.name|truncatewords:5 }}</h3>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}


    <script>
        function sentRentForm()
        {
            let form = document.getElementById("add_to_cart_form");
            form.action = "{% url 'Wsports:rent_product' product_id=product.id %}";
            form.method = "GET";
            form.submit();


        }

        let rent_btn = document.getElementById("btn-rent");
        rent_btn.addEventListener("click", sentRentForm);



    </script>
{% endblock %}

shop/templates/profile.html
{% extends 'base.html' %}

{% block title %} Профиль {% if user.first_name and user.last_name %}- {{ user.first_name }} {{ user.last_name }} {% endif %}{% endblock %}

{% block content %}
    <div class="container mt-5">
<!--        <h2 align="center">Личная Информация</h2>-->
<!--        <p>Имя: {{ user.first_name }}</p>-->
<!--        <p>Фамилия: {{ user.last_name }}</p>-->
<!--        <p>Телефон: {{ user.phone }}</p>-->
<!--        <p>Почта: {{ user.email }}</p>-->
<!--        <h2 align="center">Адреса</h2>-->
<!--        <ul>-->
<!--            {% for address in user.address_set.all %}-->
<!--                <li>-->
<!--                    {{ address.city }}, {{ address.street }}, д. {{ address.house }}, кв/оф {{ address.flat }}-->
<!--                </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--        <h2 align="center">История заказов</h2>-->
<!--            {% for order in user.cart_list.all %}-->
<!--                {% if order.products.all %}-->
<!--                    <p>Номер: #{{ order.id }}</p>-->
<!--                    <ul>-->
<!--                        {% for product in order.products.all %}-->
<!--                            <li>{{ product.name|truncatewords:4 }}, Кол-во: {{ product.count }}, Цена: {{ product.price }}</li>-->
<!--                        {% endfor %}-->
<!--                        <li style="color: grey;">Сумма заказа: {{ cart.get_total_amount }}</li>-->
<!--                    </ul>-->
<!--                {% endif %}-->
<!--            {% endfor %}-->
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#information">Информация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#addresses">Адресы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#history">История заказов</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#rent">Аренда</a>
          </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="information">
                <h2 align="center">Личная Информация</h2>
                <p>Имя: {{ user.first_name }}</p>
                <p>Фамилия: {{ user.last_name }}</p>
                <p>Телефон: {{ user.phone }}</p>
                <p>Почта: {{ user.email }}</p>
            </div>
            <div class="tab-pane fade hide" id="addresses">
                <h2 align="center">Адресы</h2>
                    {% for address in user.address_set.all %}
                    <li>
                        {{ address.city }}, {{ address.street }}, д. {{ address.house }}, кв/оф {{ address.flat }}
                        <a href="{% url 'Wsports:delete_address_url' address.id %}">Удалить</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tab-pane fade hide" id="history">
                <h2 align="center">История заказов</h2>
            {% for cart in carts %}
                {% if cart.products_variants.all %}
                    <p>Номер: #{{ cart.id }}</p>
                    <ul>
                        {% for order in cart.order_set.all %}
                            <li>{{ order.product_variant.product.name|truncatewords:4 }}, Кол-во: {{ order.count }}, Цена: {{ order.product_variant.product.price }}
                                {% for attr in order.product_variant.variant_values.all %}{{ attr }}: {{ attr.value }}, {% endfor %}
                            </li>
                        {% endfor %}
                        <li style="color: grey;">Сумма заказа: {{ cart.get_total_amount }} руб.</li>
                    </ul>
                {% endif %}
            {% endfor %}
            </div>
            <div class="tab-pane fade hide" id="rent">
                <h2 align="center">Аренда</h2>
                {% for rent in rent_set %}
                    <p>{{ forloop.counter }}. <a href="{% url 'Wsports:product_url' rent.product_variant.product.name %}">{{ rent.product_variant }}</a>
                        <br>&nbsp;&nbsp;Начальная дата: {{ rent.begin_date }}
                        <br>&nbsp;&nbsp;Длительность: {{ rent.duration }} дней

                        {% if rent.get_rent_days_left < 0 %}
                            <span style="color: red;"> - Просрочено</span>
                        {% else %}
                            <br>&nbsp;&nbsp;Осталось: {{ rent.get_rent_days_left }} дней
                        {% endif %}
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/success.html
{% extends 'base.html' %}

{% block title %} Спасибо за покупку {% endblock %}

{% block content %}
<div align="center" class="mt-5">
    {% if error %}
        <p>{{ error }}</p>
    {% else %}
        <h1>Спасибо за покупку!</h1>
        <p>Ваш заказ #{{ cart.id }}. Ожидайте информации от менеджера нашего магазина</p>
        <div class="row">
            <div class="col-6">
                <a href="/" style="color: black;">Вернуться на главную</a>
            </div>
            <div class="col-6">
                <a href="{% url 'Wsports:profile' %}" style="color: black;">В историю заказов</a>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}


<!--посмотретб tabs бутстрапа для профиля-->