core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from shop import views

# handler404 = "shop.views.handler404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = 'Wsports'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index_url'),
    path('brands/<slug:brand_name>/', views.BrandProductsView.as_view(), name='brand_url'),
    path('categories/<str:category_name>/', views.CategoryProductsView.as_view(), name='category_url'),
    path('product/<str:product_name>/', views.ProductDetailView.as_view(), name='product_url'),
    path('test_form/', views.test_model_form, name='form_url'),
    path('accounts/profile/', views.ProfileView.as_view(), name='profile'),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),
    path('add_to_cart/<int:product_id>', views.AddToCartView.as_view(), name='add_to_cart_url'),
    path('cart/delete/<int:product_variant_id>/', views.DeleteFromCartView.as_view(), name='product_delete_url'),
    path('cart/', views.CartView.as_view(), name='cart_url'),
    path('shipping_and_payment/', views.ShippingAndPaymentView.as_view(), name='shipping_and_payment_url'),
    path('change_count/<int:product_variant_id>/<str:count>/', views.ChangeCountView.as_view(), name='change_count_url'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout_url'),
    path('purchase/<int:id>', views.PurchaseView.as_view(), name='purchase_url'),
    path('success/', views.PaymentSuccessView.as_view(), name='payment_success_url'),
    path('failure/', views.PaymentFailureView.as_view(), name='payment_failure_url'),
    path('result/', views.PaymentResultView.as_view(), name="payment_result_url"),
    path('get_attribute_format/', views.GetAttributeFormatView.as_view(), name="get_attribute_format_url"),
    path('rent_product/<int:product_id>/', views.RentProductView.as_view(), name="rent_product"),
    path('rent/<int:product_variant_id>/', views.AcceptProductRentView.as_view(), name="rent_acception_url"),
    path('order_finish/', views.OrderFinishView.as_view(), name="order_finish_url"),
    path('delete_address/<int:address_id>/', views.DeleteAddressView.as_view(), name="delete_address_url"),
    path('find_weather_forecast/', views.FindWeatherForecastView.as_view(), name="find_weather_forecast_url"),
    path('search_for_products/', views.SearchForProducts.as_view(), name="search_for_products_url"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" href="/static/images/xtra/favicon.png" type="image/x-icon">
    {% block styles %} {% endblock %}
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  {% block script %}{% endblock %}
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Wsports</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if user.is_authenticated %}
        <li class="nav-item">
        {% if user.get_full_name %}
          <a href="{% url 'Wsports:profile' %}"><div style="color: white" class="mt-2">{{ user.get_full_name }}</div></a>
        {% else %}
          <a href="{% url 'Wsports:profile' %}"><div style="color: white" class="mt-2">{{ user.username }}</div></a>
        {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout/">Выход</a>
        </li>
      {% else %}


      <li class="nav-item">
        <a class="nav-link" href="/accounts/login/">Вход</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/accounts/register/">Регистрация</a>
      </li>
      {% endif %}
    </ul>
    <a href="{% url 'Wsports:cart_url' %}"><img src="/static/images/xtra/basket.png" alt="BASKET" height="40px" width="40"/></a>
    <form class="form-inline my-2 my-lg-0" action="{% url 'Wsports:search_for_products_url' %}" method="GET">
      {{ search_form.as_p }}
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
    </form>
  </div>
</nav>
<br><br>
{% block content %}
{% endblock %}
<footer class="container pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">&copy; 2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Lorem</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">VK</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Контакты</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="https://vk.com/reskier">VK</a></li>
          <li><a class="text-muted" href="#">filipp05@inbox.ru</a></li>
          <li><a class="text-muted" href="#">filipp05050505@gmail.com</a></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>